version: '3.8'

services:
  redis-node-1:
    image: redis:7
    ports:
      - "7001:6379"
    command: ["redis-server", "--port", "6379", "--cluster-enabled", "yes", "--cluster-config-file", "nodes.conf", "--cluster-node-timeout", "5000", "--appendonly", "yes"]
    volumes:
      - ./data/node-1:/data

  redis-node-2:
    image: redis:7
    ports:
      - "7002:6379"
    command: ["redis-server", "--port", "6379", "--cluster-enabled", "yes", "--cluster-config-file", "nodes.conf", "--cluster-node-timeout", "5000", "--appendonly", "yes"]
    volumes:
      - ./data/node-2:/data

  redis-node-3:
    image: redis:7
    ports:
      - "7003:6379"
    command: ["redis-server", "--port", "6379", "--cluster-enabled", "yes", "--cluster-config-file", "nodes.conf", "--cluster-node-timeout", "5000", "--appendonly", "yes"]
    volumes:
      - ./data/node-3:/data
